// Code generated by gobind. DO NOT EDIT.

// Java class iden3mobile.BytesArray is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/arnaubennassar/go-playground/mobile/mobile
package iden3mobile;

import go.Seq;

/**
 * TODO. HAVE A LOOK AT CODE GEN
 */
public final class BytesArray implements Seq.Proxy {
	static { Iden3mobile.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	public BytesArray() {
		this.refnum = __NewBytesArray();
		Seq.trackGoRef(refnum, this);
	}
	
	private static native int __NewBytesArray();
	
	BytesArray(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public native void append(byte[] bs);
	public native byte[] get(long i);
	public native long len();
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof BytesArray)) {
		    return false;
		}
		BytesArray that = (BytesArray)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("BytesArray").append("{");
		return b.append("}").toString();
	}
}

