// Code generated by gobind. DO NOT EDIT.

// Java class iden3mobile.Callback is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/arnaubennassar/go-playground/mobile/mobile
package iden3mobile;

import go.Seq;

public interface Callback {
	public void verifierResponse(boolean p0, java.lang.Exception p1);
	
}

