// Code generated by gobind. DO NOT EDIT.

// Java class iden3mobile.Event is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/arnaubennassar/go-playground/mobile/mobile
package iden3mobile;

import go.Seq;

public interface Event {
	public void onIssuerResponse(String p0, String p1, byte[] p2, java.lang.Exception p3);
	
}

