// Code generated by gobind. DO NOT EDIT.

// Java class iden3mobile.Iden3mobile is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/arnaubennassar/go-playground/mobile/mobile
package iden3mobile;

import go.Seq;

public abstract class Iden3mobile {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Iden3mobile() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	private static final class proxyCallback implements Seq.Proxy, Callback {
		private final int refnum;
		
		@Override public final int incRefnum() {
		      Seq.incGoRef(refnum, this);
		      return refnum;
		}
		
		proxyCallback(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
		
		public native void verifierResponse(boolean p0, java.lang.Exception p1);
	}
	private static final class proxyEvent implements Seq.Proxy, Event {
		private final int refnum;
		
		@Override public final int incRefnum() {
		      Seq.incGoRef(refnum, this);
		      return refnum;
		}
		
		proxyEvent(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
		
		public native void onIssuerResponse(String p0, String p1, byte[] p2, java.lang.Exception p3);
	}
	private static final class proxyTicketsMapInterface implements Seq.Proxy, TicketsMapInterface {
		private final int refnum;
		
		@Override public final int incRefnum() {
		      Seq.incGoRef(refnum, this);
		      return refnum;
		}
		
		proxyTicketsMapInterface(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
		
		public native void f(Ticket p0) throws Exception;
	}
	
	
	public static native BytesArray newBytesArray();
	/**
	 * NewIdentity creates a new identity
	this funciton is mapped as a constructor in Java
	 */
	public static native Identity newIdentity(String storePath, String pass, BytesArray extraGenesisClaims, Event e) throws Exception;
	/**
	 * NewIdentityLoad loads an already created identity
	this funciton is mapped as a constructor in Java
	 */
	public static native Identity newIdentityLoad(String storePath, Event e) throws Exception;
}
