// Code generated by gobind. DO NOT EDIT.

// Java class iden3mobile.TicketsMap is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/arnaubennassar/go-playground/mobile/mobile
package iden3mobile;

import go.Seq;

public final class TicketsMap implements Seq.Proxy {
	static { Iden3mobile.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	TicketsMap(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public TicketsMap() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public native void forEach(TicketsMapInterface handler) throws Exception;
	public native Ticket get(String key) throws Exception;
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof TicketsMap)) {
		    return false;
		}
		TicketsMap that = (TicketsMap)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("TicketsMap").append("{");
		return b.append("}").toString();
	}
}

