// Code generated by gobind. DO NOT EDIT.

// Java class iden3mobile.Ticket is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/arnaubennassar/go-playground/mobile/mobile
package iden3mobile;

import go.Seq;

public final class Ticket implements Seq.Proxy {
	static { Iden3mobile.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	Ticket(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public Ticket() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native String getId();
	public final native void setId(String v);
	
	public final native long getLastChecked();
	public final native void setLastChecked(long v);
	
	public final native String getType();
	public final native void setType(String v);
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof Ticket)) {
		    return false;
		}
		Ticket that = (Ticket)o;
		String thisId = getId();
		String thatId = that.getId();
		if (thisId == null) {
			if (thatId != null) {
			    return false;
			}
		} else if (!thisId.equals(thatId)) {
		    return false;
		}
		long thisLastChecked = getLastChecked();
		long thatLastChecked = that.getLastChecked();
		if (thisLastChecked != thatLastChecked) {
		    return false;
		}
		String thisType = getType();
		String thatType = that.getType();
		if (thisType == null) {
			if (thatType != null) {
			    return false;
			}
		} else if (!thisType.equals(thatType)) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getId(), getLastChecked(), getType()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("Ticket").append("{");
		b.append("Id:").append(getId()).append(",");
		b.append("LastChecked:").append(getLastChecked()).append(",");
		b.append("Type:").append(getType()).append(",");
		return b.append("}").toString();
	}
}

