# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'iden3Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iden3Example
  pod 'iden3', :path => '../iden3'

  target 'iden3ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iden3ExampleUITests' do
    # Pods for testing
  end

end
